version: '{build}'
shallow_clone: true

platform: Any CPU
configuration: Release
image: Visual Studio 2017

install:
  - nuget restore admxgen.sln

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\v3-cache'

build:
  parallel: true
  project: admxgen.sln
  verbosity: minimal

test:
  assemblies:
    only:
      - '**\*-tests.dll'

deploy: off

notifications:
  - provider: Email
    to:
      - jhurren@fslogix.com
    on_build_status_changed: true
    on_build_success: false
    on_build_failure: false