version: '{build}'
shallow_clone: true

platform: Any CPU
configuration: Release
image: Visual Studio 2017

install:
  - nuget restore admxgen.sln

build:
  project: admxgen.sln

test:
  assemblies:
    only:
      - '**\*-tests.dll'

deploy: off

notifications:
  - provider: Email
    to:
      - jhurren@fslogix.com
    on_build_status_changed: true
    on_build_success: false
    on_build_failure: false